### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [bbatliner/electron-wrapper#1]
After installing the dependencies:
rimraf, ncp, mustache, mkdirp, electron-packager, electron-localshortcut, command-line-args

When running electron-wrapper -h i have this error `No such file or directory`. Are those dependencies correct?

**Comment by bbatliner** [comment]
Hi Phillip, those dependencies are correct. If you're having issues with the help flag, my guess is that you didn't install the npm module globally.

Use `npm install -g electron-wrapper` (the -g flag means global) and try `electron-wrapper -h` again.

Let me know if there's anything else I can do to help!

**Comment by phillip-white-sociomantic** [comment]
@bbatliner Unfortunately the same problem. I install all the discrepancies with `sudo npm install -g <npm package>`. And then electron wrapper with `npm install -g electron-wrapper`. I still have the same error:

```
$ sudo electron-wrapper -h
: No such file or directory
```

**Comment by phillip-white-sociomantic** [comment]
I am using https://www.npmjs.com/package/nativefier, and it works fine. We can close this issue. Very strange it did not work though...

Thanks for the assistance @bbatliner
