### ISSUE TITLE
Comic Sans font not supported

### ISSUE THREAD

**Issue by vingkan** [bbatliner/electron-wrapper#2]
hello

I tried to "wrap" (that's the verb, right?) a window from a brilliant hack called funfacts.js but electron-wrapper changed the font from comic sans to times new roman

please fix
# thank

**Comment by bbatliner** [comment]
I was unable to replicate the issue and it's not intended behavior. Closing this issue.

#welcome

**Comment by vingkan** [comment]
okay thank you for your hard work on this project that has received thousands of downloads
