### ISSUE TITLE
env: node\r not found

### ISSUE THREAD

**Issue by rickychilcott** [bbatliner/electron-wrapper#4]
Love the tool.

I was playing with this on a Mac and ran into an issue trying to use it because it looks like perhaps it was developed on a Windows computer, assuming I'm understanding the issue correctly.

When I used the `dos2linux` command line tool to strip the new line characters, it worked ok.  Would you be interested in reviewing https://help.github.com/articles/dealing-with-line-endings/ to see what might be the best practice around supporting multiple line endings?

**Comment by bbatliner** [comment]
Yea, absolutely. I'm surprised my GitHub settings aren't configured correctly.

If I may ask, what is your use case for electron-wrapper? I developed it for personal use but found I could add websites to my desktop and launch them as separate windows natively in Chrome, without the need for something like electron-wrapper.

**Comment by rickychilcott** [comment]
Hey @bbatliner after reviewing some of the issues and googling a bit more, my use case is mostly what [nativefier](https://github.com/jiahaog/nativefier) is after. Since that's my use case, I'm not sure it's necessary to make any changes. I thought you'd appreciate knowing that Mac/Linux users may run into build issues.

**Comment by bbatliner** [comment]
Yup, that project seems much farther along than this one! Good luck and thank you for the heads up.
